### ISSUE TITLE
[v6] Module parse failed: Unexpected character '#' when using Create-React-App

### ISSUE THREAD

**Issue by sabotag** [wojtekmaj/react-pdf#1043]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Our team is waiting for a new version of react-pdf with a new build of pdfjs-dist, which has a fix for Hebrew, so for the test, we tried to install the 6th version of react-pdf but after installation we got the following error 
![Screenshot 2022-08-29 at 14 16 25](https://user-images.githubusercontent.com/3120322/187189385-dc98d259-6107-4833-a016-3eb25f31019f.png)

### Steps to reproduce

install 
react-pdf 16 or 17
react-scripts: 3.4.4
implement react-pdf@v6.0.0-beta.3

### Expected behavior

-

### Actual behavior

```
./node_modules/pdfjs-dist/build/pdf.js 1390:17
Module parse failed: Unexpected character '#' (1390:17)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|         class PDFDocumentLoadingTask {
>           static #docId = 0;
| 
|           constructor() {
```

### Additional information

how can we solve this problem? Thank you

[DEMO](https://codesandbox.io/s/react-pdf-v6-itjfzl?file=/src/App.js)

### Environment

- **Browser (if applicable)**: chrome
- **React-PDF version**: 6
- **React version**: 17
- **react-scripts**: 3.4.4

**Comment by wojtekmaj** [comment]
Hmmm, tried running 6.0.0-beta.3 with my Create React App 5 sample app and it went without any issues. I suspect react-scripts 3.4.4 might be a bit too old 🤔

**Comment by quarryman** [comment]
Same issue here.
As far as I am concerned react-scrits 3.x.x still seems to be pretty common these days and migrating to 4.x branch is not always possible.

Any chances to get some help with this?

**Comment by wojtekmaj** [comment]
Maybe it's possible to update Babel manually? I hope they didn't pin Babel version in CRA?

**Comment by FilipKittnar** [comment]
Hello, I am on react-scripts 4.0.3 and I have the very same problem.

**Comment by wojtekmaj** [comment]
We have tests for CRA 5, CRA 4 might need additional configuration which I haven't discovered yet

**Comment by SauravPatel3042** [comment]
This is my code:
import * as React from "react";
import { Viewer, Worker } from "@react-pdf-viewer/core";
import { defaultLayoutPlugin } from "@react-pdf-viewer/default-layout";

import "@react-pdf-viewer/core/lib/styles/index.css";
import "@react-pdf-viewer/default-layout/lib/styles/index.css";

const PdfPreview = () => {
  const defaultLayoutPluginInstance = defaultLayoutPlugin();
  return (
    <div className="w-100 h-100">
      <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.15.349/legacy/build/pdf.worker.js">
        <div>
          <Viewer
            fileUrl={`${process.env.PUBLIC_URL}/pdf-open-parameters.pdf`}
            plugins={[defaultLayoutPluginInstance]}
          />
        </div>
      </Worker>
    </div>
  );
};

export default PdfPreview;

Error
![image](https://user-images.githubusercontent.com/118245431/201836982-f7774c8d-47b5-4382-854e-029999f5f0cd.png)

This is the package how I install
"@react-pdf-viewer/core": "^3.8.0",
"@react-pdf-viewer/default-layout": "^3.8.0",
"pdfjs-dist": "^3.0.279",
"react": "^17.0.2",
"react-script": "^2.0.5",

**Comment by SauravPatel3042** [comment]
This is my code 
import React, { useState } from "react";
import { Document, Page } from "react-pdf/dist/esm/entry.webpack";

import "react-pdf/dist/esm/Page/AnnotationLayer.css";
import "react-pdf/dist/esm/Page/TextLayer.css";

const PdfPreview = ({ data }) => {
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  const onDocumentLoadSuccess = ({ numPages }) => {
    setNumPages(numPages);
  };

  const goToPrevPage = () =>
    setPageNumber(pageNumber - 1 <= 1 ? 1 : pageNumber - 1);

  const goToNextPage = () =>
    setPageNumber(pageNumber + 1 >= numPages ? numPages : pageNumber + 1);

  return (
    <div>
      <nav>
        <button onClick={goToPrevPage}>Prev</button>
        <button onClick={goToNextPage}>Next</button>
        <p>
          Page {pageNumber} of {numPages}
        </p>
      </nav>

      <Document file={data.path} onLoadSuccess={onDocumentLoadSuccess}>
        <Page pageNumber={pageNumber} />
      </Document>
    </div>
  );
};

export default PdfPreview;

Error 
![image](https://user-images.githubusercontent.com/118245431/201843293-10d09b32-a5fd-47f6-bd59-2b0051cec093.png)

packages

"react-pdf": "^6.0.3",
"pdfjs-dist": "^3.0.279",

please give a solution

**Comment by victors1681** [comment]
same thing in storybook

```
"@storybook/react": "^6.5.13",
"react-pdf": "^6.1.1"

```


```
ERROR in ./node_modules/pdfjs-dist/build/pdf.js 1413:9
Module parse failed: Unexpected character '#' (1413:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class PDFDocumentLoadingTask {
>   static #docId = 0;
| 
```

I also tried to add `"@babel/plugin-proposal-class-static-block", ` but did not work.

**Comment by veddermatic** [comment]
Another data point; I'm seeing this with:
```
"react-scripts": "^4.0.3",
"react": "^16.12.0",
"react-pdf": "^6.2.0",
"typescript": "^4.2.4",
```

**Comment by clmz** [comment]
@victors1681 
Dif you figure out any solution? I have the same issue with storybook.

**Comment by Kajanan02** [comment]
Did you figure out any solution? I have also this same issue :(

**Comment by assdi54** [comment]
also have same issue 
            `./node_modules/pdfjs-dist/build/pdf.js 1410:17
            Module parse failed: Unexpected character '#' (1410:17)
            File was processed with these loaders:
             * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
            You may need an additional loader to handle the result of these loaders.
            | 
            |         class PDFDocumentLoadingTask {
            >           static #docId = 0;
            | 
            |           constructor() {`

**Comment by lag-of-death** [comment]
Had the same issue and found no solution (had to revert to react-pdf version 5.0.0)

**Comment by apendua** [comment]
I think that this problem is not specific to `create-react-app`. Most of the tooling will not transform code that comes from `node_modules`, unless you explicitly ask them to do so. Clearly, private class properties are not supported by all browsers yet so if some project is willing to support older browsers as well they will not be able to include this package easily. I am wondering if it would be possible to have an `es5` or perhaps `es6` compatible builds distributed along with this package.

**Comment by apendua** [comment]
Ok, so apparently `pdfjs-dist` actually ships with builds for legacy browsers, but this needs to be imported differently, e.g.
```
import * as pdfjsLib from 'pdfjs-dist/legacy/build/pdf';
```
Perhaps it would be more prudent if `react-pdf` could import those legacy (more compatible) builds instead?

**Comment by walpolsh** [comment]
getting the same error here:
```
./node_modules/pdfjs-dist/build/pdf.js 1540:17
Module parse failed: Unexpected character '#' (1540:17)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|         class PDFDocumentLoadingTask {
>           static #docId = 0;
| 
|           constructor() {

```

```
    "react-pdf": "^6.2.0",
    "@types/react-pdf": "^6.2.0", // I'm not using typescript in the main project, just added upon previous suggestion.
    "react-scripts": "4.0.0",
```

Oddly enough it was working until I changed branches and it was totally broken when I switched back.

**Comment by sai-gillingham** [comment]
I've had this error on react-pdf above `4.2.0` so if you are desperate to get this implemented in a hurry I would suggest downgrading to `4.2.0`.

Currently running on:
`react-scripts: 4.0.3`

**Comment by evanjmg** [comment]
Anyone have any build solutions?

**Comment by Nubuck** [comment]
I managed to get ```react-pdf 6.2.2``` to work with deps ```webpack 4.46.0``` and ```@babel/preset-env 7.20.2```

I found using the ```include``` property of the babel rule and adding pdfjs-dist after the source built and rendered successfully.
Heres and snip of the webpack config for the rule:
```javascript
const np = require('path')

module.exports = {
  // ...
  module: {
    // ...
    rules: [
      {
        test: /\.(mjs|jsx|js)$/,
        include: [
          np.resolve('src'),
          // babel-env has all the presets to build pdfjs, just needs to be included
          np.resolve('node_modules/pdfjs-dist/build'),
        ],
        use: [
          {
            loader: 'babel-loader',
            options: {
              cacheDirectory: true,
              babelrc: false,
              configFile: false,
              presets: [
                '@babel/preset-env',
                // ....
              ],
              plugins: [
                '@babel/plugin-syntax-dynamic-import',
                // ...
              ],
            },
          },
        ],
      },
    ],
  },
}
```

I hope that helps someone that was also stuck on the ```Module parse failed: Unexpected character '#' (1413:9)``` build error

**Comment by aviadavi** [comment]
did anyone happen to get react-pdf 6.2.2 working via webpack 4? the recommendation below of @Nubuck didn't help. thanks.

**Comment by briandiaz** [comment]
This is still failing...

**Comment by judebaptista18** [comment]
@evanjmg Update to webpack 5 it should solve this issue.

**Comment by tamourali** [comment]
You Needs to downgrade you package version to.
> **("pdfjs-dist": "2.5.207")**
 This works fine for me.

**Comment by ionutmiftode** [comment]
after 2 days on this issue I fixed it thanks to @yhunglee's [comment](https://github.com/wojtekmaj/react-pdf/issues/1043#issuecomment-1318344345).

So I have a CRA with react-scripts@4.0.3 and I installed:
```
"pdfjs-dist": "2.6.347",
"react-pdf": "5.3.2",
```
and then in the .jsx file I imported like this:

`import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';`

Hope this helps!

**Comment by RomualdMashup** [comment]
Hello. I have the same issue with Storybook and react-pdf 6.2.2.
And I can't find where i should edit Babel configuration...

**Comment by mikhail-uchi-ru** [comment]
Hola!
Any updates on this?

**Comment by maesiegrist** [comment]
G'day - wondering if there is an ETA for this bug to be fixed? TIA

**Comment by tukuna30** [comment]
I had same issue in my React app with react-scripts 4.0.3 
To render PDF instead of using this lib just used `<object> Jsx tag `

Sample usage
` 
import pdfFile from '../../../test.pdf';

<object
                data={pdfFile}
                type="application/pdf"
                width="100%"
                 height="100%">
  </object>`

**Comment by AndrejGajdos** [comment]
I was getting this issue in another library `pdf-viewer-reactjs@2.1.2` that installs `pdfjs-dist@2.1.x`. @Nubuck solution helped me to compile the project with Webpack, but my project was crashing because of an issue:

`TypeError: Cannot read properties of undefined...`

I added `pdfjs-dist@@2.6.347` into package.json and also added "pdfjs-dist": "2.6.347" into yarn resolutions so pdf-viewer-reactjs uses `pdfjs-dist@@2.6.347` instead of `pdfjs-dist@2.1.x` and everything works now.

**Comment by ngwszsd** [comment]
If you want to solve this problem you need to switch to "react-pdf": "^5.3.2" version, [this issure](https://github.com/wojtekmaj/react-pdf/issues/1043) may be helpful for you, or see my [codebox](https://codesandbox.io/p/sandbox/umi3-8vtzy1?file=%2Fsrc%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A12%7D%5D)

**Comment by ShenHueTzu** [comment]
I have this problem too, when I upgrade `react-pdf` to v6.2.0.
Any update ? 

```
 react: ^16.8.2,
react-pdf: 6.2.0,
```

**Comment by Realnaru** [comment]
./node_modules/pdfjs-dist/build/pdf.js 1198:17
Module parse failed: Unexpected character '#' (1198:17)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|         }
|         class PDFDocumentLoadingTask {
>           static #docId = 0;
|           constructor() {
|             this._capability = (0, _util.createPromiseCapability)();  

react: 17.0.2,
react-pdf: 6.2.2,
typescript: 4.2.4,

**Comment by ngwszsd** [comment]
> ./node_modules/pdfjs-dist/build/pdf.js 1198:17 Module parse failed: Unexpected character '#' (1198:17) File was processed with these loaders:
> 
> * ./node_modules/babel-loader/lib/index.js
>   You may need an additional loader to handle the result of these loaders.
>   |         }
>   |         class PDFDocumentLoadingTask {
> 
> > ```
> >       static #docId = 0;
> > ```
> 
> | constructor() { | this._capability = (0, _util.createPromiseCapability)();
> 
> react: 17.0.2, react-pdf: 6.2.2, typescript: 4.2.4,

just use 5.3.2

**Comment by ShenHueTzu** [comment]
> > ./node_modules/pdfjs-dist/build/pdf.js 1198:17 Module parse failed: Unexpected character '#' (1198:17) File was processed with these loaders:
> > 
> > * ./node_modules/babel-loader/lib/index.js
> >   You may need an additional loader to handle the result of these loaders.
> >   |         }
> >   |         class PDFDocumentLoadingTask {
> > 
> > > ```
> > >       static #docId = 0;
> > > ```
> > 
> > 
> > | constructor() { | this._capability = (0, _util.createPromiseCapability)();
> > react: 17.0.2, react-pdf: 6.2.2, typescript: 4.2.4,
> 
> just use 5.3.2

But I need to use "devicePixelRatio" this props.
Is there any other way to use version 5.3.2 and change pixel ratio manual ?

**Comment by yycfollow35** [comment]
> > ./node_modules/pdfjs-dist/build/pdf.js 1198:17 Module parse failed: Unexpected character '#' (1198:17) File was processed with these loaders:
> > 
> > * ./node_modules/babel-loader/lib/index.js
> >   You may need an additional loader to handle the result of these loaders.
> >   |         }
> >   |         class PDFDocumentLoadingTask {
> > 
> > > ```
> > >       static #docId = 0;
> > > ```
> > 
> > 
> > | constructor() { | this._capability = (0, _util.createPromiseCapability)();
> > react: 17.0.2, react-pdf: 6.2.2, typescript: 4.2.4,
> 
> just use 5.3.2

It really works.

**Comment by ngwszsd** [comment]
> > > ./node_modules/pdfjs-dist/build/pdf.js 1198:17 Module parse failed: Unexpected character '#' (1198:17) File was processed with these loaders:
> > > 
> > > * ./node_modules/babel-loader/lib/index.js
> > >   You may need an additional loader to handle the result of these loaders.
> > >   |         }
> > >   |         class PDFDocumentLoadingTask {
> > > 
> > > > ```
> > > >       static #docId = 0;
> > > > ```
> > > 
> > > 
> > > | constructor() { | this._capability = (0, _util.createPromiseCapability)();
> > > react: 17.0.2, react-pdf: 6.2.2, typescript: 4.2.4,
> > 
> > 
> > just use 5.3.2
> 
> But I need to use "devicePixelRatio" this props. Is there any other way to use version 5.3.2 and change pixel ratio manual ?

import { Document, Page, pdfjs   } from "https://github.com/wojtekmaj/react-pdf";
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

if you use create-react-app ，must add this
you can see my  any sample  https://gitee.com/garvinew/react-read-pdf-sample

**Comment by Novizh** [comment]
> If you want to solve this problem you need to switch to "react-pdf": "^5.3.2" version, [this issure](https://github.com/wojtekmaj/react-pdf/issues/1043) may be helpful for you, or see my [codebox](https://codesandbox.io/s/determined-chihiro-3xe7j9) ！！！！If the codebox runs incorrectly, it is possible to export the project run！！！！

This works for me,  thanks a lot buddy!

**Comment by cdk0507** [comment]
Anything fixed in version 6?
In version 5 there is no TextLayer.css.

**Comment by fr11nik** [comment]
I fix this issue via updating react-scripts from `@4.0.1` to `@5.0.1`

**Comment by wojtekmaj** [comment]
CRA 4 is now 2.5 years old, CRA 5 is almost 2 years old. I have no intention or capacity of supporting v4. If you need to use React-PDF with CRA 4, use older React-PDF versions.

**Comment by Granddevv** [comment]
I am using v7.3.3, but still getting this error.

  ModuleParseError: Module parse failed: Unexpected character '' (1:0)

  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

  (Source code omitted for this binary file)

![image](https://github.com/wojtekmaj/react-pdf/assets/31965726/12a0f5af-3cad-4cfc-aa20-8bd7df69c18f)

**Comment by Granddevv** [comment]
Nevermind, it works. The library looks good.

**Comment by aziz1234** [comment]
> Nevermind, it works. The library looks good.

How did you make it work?

**Comment by rramos-j** [comment]
> Ok, so apparently `pdfjs-dist` actually ships with builds for legacy browsers, but this needs to be imported differently, e.g.
> 
> ```
> import * as pdfjsLib from 'pdfjs-dist/legacy/build/pdf';
> ```
> 
> Perhaps it would be more prudent if `react-pdf` could import those legacy (more compatible) builds instead?

This was really helpful, thanks!

**Comment by lingduzero** [comment]
one possible solution, 

import {pdfjs} from 'react-pdf';
import PDFJSWorker from 'pdfjs-dist/build/pdf.worker.entry';

pdfjs.GlobalWorkerOptions.workerSrc = PDFJSWorker;

Also set webpack.config.js
attributes alias
add 
'pdfjs-dist': path.resolve(___dirname, 'node_modules/pdfjs-dist/legacy')

works good with webpack 4 and react 16 for react-pdf V6, if want to use V7 please use webpack5

**Comment by MachuKP** [comment]
Version5 has a case when I view one of a pdf files, It cause browser slow, lagging, and make it doesn't reposne. I've fixed the problem with upgrade to version 6 and found Module parse failed: Unexpected character '#'. when i update my nextjs version to "next": "^11.1.4" it fixed the error.
here my environment
"next": "^11.1.4"
"react": "^17.0.2"
"react-pdf": "^6.2.2"

**Comment by nettieJin** [comment]
add 
transpileDependencies: ['pdfjs-dist']
in your vue.config.js if you use vue and pdfjs-dist

**Comment by pachopa** [comment]
> I managed to get `react-pdf 6.2.2` to work with deps `webpack 4.46.0` and `@babel/preset-env 7.20.2`
> 
> I found using the `include` property of the babel rule and adding pdfjs-dist after the source built and rendered successfully. Heres and snip of the webpack config for the rule:
> 
> ```js
> const np = require('path')
> 
> module.exports = {
>   // ...
>   module: {
>     // ...
>     rules: [
>       {
>         test: /\.(mjs|jsx|js)$/,
>         include: [
>           np.resolve('src'),
>           // babel-env has all the presets to build pdfjs, just needs to be included
>           np.resolve('node_modules/pdfjs-dist/build'),
>         ],
>         use: [
>           {
>             loader: 'babel-loader',
>             options: {
>               cacheDirectory: true,
>               babelrc: false,
>               configFile: false,
>               presets: [
>                 '@babel/preset-env',
>                 // ....
>               ],
>               plugins: [
>                 '@babel/plugin-syntax-dynamic-import',
>                 // ...
>               ],
>             },
>           },
>         ],
>       },
>     ],
>   },
> }
> ```
> 
> I hope that helps someone that was also stuck on the `Module parse failed: Unexpected character '#' (1413:9)` build error



> I managed to get `react-pdf 6.2.2` to work with deps `webpack 4.46.0` and `@babel/preset-env 7.20.2`
> 
> I found using the `include` property of the babel rule and adding pdfjs-dist after the source built and rendered successfully. Heres and snip of the webpack config for the rule:
> 
> ```js
> const np = require('path')
> 
> module.exports = {
>   // ...
>   module: {
>     // ...
>     rules: [
>       {
>         test: /\.(mjs|jsx|js)$/,
>         include: [
>           np.resolve('src'),
>           // babel-env has all the presets to build pdfjs, just needs to be included
>           np.resolve('node_modules/pdfjs-dist/build'),
>         ],
>         use: [
>           {
>             loader: 'babel-loader',
>             options: {
>               cacheDirectory: true,
>               babelrc: false,
>               configFile: false,
>               presets: [
>                 '@babel/preset-env',
>                 // ....
>               ],
>               plugins: [
>                 '@babel/plugin-syntax-dynamic-import',
>                 // ...
>               ],
>             },
>           },
>         ],
>       },
>     ],
>   },
> }
> ```
> 
> I hope that helps someone that was also stuck on the `Module parse failed: Unexpected character '#' (1413:9)` build error

This solution worked for me. I installed "babel-loader": "^8.3.0" and added the below code into next.config.js (I use next.js 9.5.5)

config.module.rules.push({
      test: /\.(mjs|jsx|js)$/,
      include: [
        path.resolve('src'),
        // babel-env has all the presets to build pdfjs, just needs to be included
        path.resolve('node_modules/pdfjs-dist/build')
      ],
      use: [
        {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true,
            babelrc: false,
            configFile: false,
            presets: ['@babel/preset-env'],
            plugins: ['@babel/plugin-syntax-dynamic-import']
          }
        }
      ]
    });

Thank you so much!!!!

**Comment by romanpastu** [comment]
Another solution is using esbuild-loader with target es2015 , seems to fix most stuff.
Helped me bring react-pdf from v5 to v8

I specifically needed this line to make it work

```
            {
                test: /pdfjs-dist\/build\/pdf.js/,
                loader: 'esbuild-loader',
                options: {
                    target: 'es2015',
                },
            },
```

Babel seemed to be way messier

**Comment by haohuaZhang** [comment]
This solution works for me, thanks a lot buddy!

> Another solution is using esbuild-loader with target es2015 , seems to fix most stuff. Helped me bring react-pdf from v5 to v8
> 
> I specifically needed this line to make it work
> 
> ```
>             {
>                 test: /pdfjs-dist\/build\/pdf.js/,
>                 loader: 'esbuild-loader',
>                 options: {
>                     target: 'es2015',
>                 },
>             },
> ```
> 
> Babel seemed to be way messier
> 
> This is using esbuild-loader : 4.2.0 react-pdf: 8.0.2

It works for me, thanks a lot!
