### ISSUE TITLE
Textlayer out of alignment

### ISSUE THREAD

**Issue by jimmythompson** [wojtekmaj/react-pdf#332]
**Description**

The textContent on this particular PDF seems out of alignment with what's rendered on the canvas, meaning copying and pasting is really difficult. This appears to be fine in vanilla PDF.js.

I'll try and look into this myself, but I'm not really sure how the whole thing works. Any help fixing this would be lovely. 😄

**Steps to reproduce**

1. Try rendering the following PDF in React PDF: http://moco17.movementcomputing.org/wp-content/uploads/2017/12/poster4-donneaud.pdf
2. Try highlighting and copying text from the abstract, a good example being "This soft input device - Musical Skin".

**Expected behavior**

It should highlight and copy the text your cursor is running over.

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser: 71.0.3578.98
 - React-PDF version: 4.0.2
 - React version: 16.4.2

**Comment by matt-erhart** [comment]
![chrome_2019-01-16_12-17-43](https://user-images.githubusercontent.com/3199847/51276156-c7369300-1988-11e9-9c3b-2a7731f26424.jpg)

Same here. I'm trying out the transform from the svg example from pdfjs: 
```js
const adjustTransMatForViewport = (viewportTransform, textItemTransform) => {
  // we have to take in account viewport transform, which includes scale,
  // rotation and Y-axis flip, and not forgetting to flip text.
  return pdfjsLib.Util.transform(
    pdfjsLib.Util.transform(viewportTransform, textItemTransform),
    [1, 0, 0, -1, 0, 0]
  );
};
```

But I can't get the xScale quite right.

**Comment by nikonet** [comment]
I had the same problem on window resize and scale changes. Solved it by calling a function that removes some of the CSS applied on the text-content page on each pageLoadSuccess. It seems to me that the default top, left and transform CSS properties on the textContent elements doesn't do anything useful. Those styles are inline, so needs to be changed with JS.
```
function removeTextLayerOffset() {
  const textLayers = document.querySelectorAll(".react-pdf__Page__textContent");
    textLayers.forEach(layer => {
      const { style } = layer;
      style.top = "0";
      style.left = "0";
      style.transform = "";
  });
}

<Page onLoadSuccess={() => removeTextLayerOffset()}/>
```

**Comment by wojtekmaj** [comment]
Tested this on my test page and it looks fairly alright. The text layer is slightly misaligned indeed so I'll have a second look at it when I'm on my desktop, but such extreme misalignments (50% of page width) is likely caused by putting Page in a too small container or similar styling issue. In such cases Canvas layer would simply expand  because it's one static element) and text layer would overflow it's 0 pixels-wide container (because it's a set of absolutely placed elements).

**Comment by joedukk** [comment]
I saw this issue as well. My temp fix was to apply the following CSS to the react-pdf__Page element -

`.react-pdf__Page.pdf-page {
    display: flex;
    justify-content: center;
  }`

**Comment by peterkmurphy** [comment]
With some PDFs, the text layer appears as invisible text across other controls on the screen - making it hard for users to interact with it. They see the mouse cursor as a textual "I" cursor even though they're over a radio button; they wouldn't be aware of the reason why unless they tried to select the control, and then see the text highlighted in reverse.

While this bug is being fixed, a suggestion for those that just need to see the PDF, but not copy and paste. That's what I'll do in the meantime.

`.react-pdf__Page__textContent {display: none;}`

**Comment by wojtekmaj** [comment]
@petermurphy You can disable text layer using `renderTextLayer` prop (see details in README). It's a much better way.

After testing for a long time I could reproduce the issue where the lines on the text layer are moved down by 1 line. No other issues were found.

Alignment before:

![obraz](https://user-images.githubusercontent.com/5426427/53697903-65b27280-3dd6-11e9-9109-f07ffc05f358.png)

Alignment after:

![obraz](https://user-images.githubusercontent.com/5426427/53697908-74992500-3dd6-11e9-81b3-2173f515e3e0.png)

I'd say it's pretty satisfactory for the means we have. This was fixed with 9dbc54ef59ced9f19fb9cbd287f4b05845ec3a46 and will be released with the next release.

**Comment by jjlauer** [comment]
@wojtekmaj -- beautiful library.  Truly appreciate all the hard work you've put into it!

I have similar text alignment issues (react-pdf v4.0.5) where some of the spans are off by hundreds of pixels to the image underneath. To be clear, many PDFs render similar to your examples above where they are super close to being aligned correctly. However, there are quite a few that are really misaligned. Here is a screenshot of the text layer being set to red:

![fireshot capture 187 - henry ford gb gmail com - localhost](https://user-images.githubusercontent.com/585730/53990266-e71b4500-40f5-11e9-987b-3f5d60cc0721.png)

The same file rendered with PDF.js in their online demo has a perfect text layer for the exact same PDF.  Just curious if react-pdf is heavily modifying the textLayer created by PDF.js, if some kind of styling I have is causing it, or something else.

I've attached the PDF with the worst misalignment.  The "Disney Store" in top portion is where its off by hundreds of pixels.

[00694003239620190303.pdf](https://github.com/wojtekmaj/react-pdf/files/2943401/00694003239620190303.pdf)

If you take the same PDF and render it in https://mozilla.github.io/pdf.js/web/viewer.html you'll notice the text layer is pixel perfect.

Taking a peek at the spans under-the-hood, in react-pdf, the "Disney Store" span looks like this:

<span style="height: 1em; font-family: sans-serif; font-size: 13.0392px; position: absolute; top: 154.094px; left: 75.1059px; transform-origin: left bottom 0px; white-space: pre; pointer-events: all;">           Disney Store # 00694</span>

PDF.js demo looks like this:

<span style="left: 76.8px; top: 157.569px; font-size: 13.3333px; font-family: monospace; transform: scaleX(0.996982);">           Disney Store # 00694</span>

Obviously the width of the two examples is different so I don't expect them to the same.  However, the version in react-pdf is setting the height, the font-family is different, and the transforms are pretty different.

**Comment by jjlauer** [comment]
@wojtekmaj I figured out the underlying cause of the misalignment in my previous example. It looks like pdf.js does font detection and swaps in monospace when it knows a serif-based font isn't being used.  They also use a transform of scaling text horizontally based on the actual font in use.  I spent some time thinking about building a PR to bring that same code in, but it turned out to be easier to delegate text layer rendering to pdf.js vs. trying to replicate what they were doing.  After testing a lot of various PDFs, the text selection via pdf.js seems to work better across a wide variety of fonts.

I implemented everything this fork: https://github.com/greenback-inc/react-pdf

If you are interested in possibly accepting this major change, I'd be happy to submit a PR.  We'd lose the ability to customize the text rendered.  Alternatively, we could allow users to select a pdf.js text layer as an alternative to the native react-pdf one.

**Comment by katiewoolston** [comment]
I'm having a similar problem, even with the simple example from the readme - the canvas and text layer are horizontally misaligned by quite a lot. I can fix it by hardcoding the width of the Page component so it's the same as the canvas. It looks like the reason for the misalignment is that the canvas is fixed width, whereas the text layer is centred in the available space. I've tried modifying the text or canvas layer css, but it gets problematic when you try to scale or rotate.

![image](https://user-images.githubusercontent.com/35474576/55778009-0d614580-5ae5-11e9-9731-02b318860d4d.png)

**Comment by Stani2980** [comment]
@nikonet  That worked like a charm in my case, aligning every site near perfect !

**Comment by Abishek-Sudhakaran** [comment]
@nikonet  superb dude..it worked well and good

**Comment by vctormb** [comment]
I've tried all the solutions here and for me it didn't work. No idea how to solve it.

**Comment by MariaBamundo** [comment]
Has this been fixed yet? I am still experiencing this issue.
![image](https://user-images.githubusercontent.com/28845265/59605851-b461ef00-90dd-11e9-856e-45a8bca635f5.png)

**Comment by MariaBamundo** [comment]
Has this been fixed yet? I am still getting this issue on the latest version. 
![image](https://user-images.githubusercontent.com/28845265/59605941-f2f7a980-90dd-11e9-8dd1-845c47830fbf.png)

**Comment by wojtekmaj** [comment]
@vctormb Most important is to ensure that your rendered PDF fits its container. If it does not, PDF layer will shrink, but text layer will not.

**Comment by vctormb** [comment]
@wojtekmaj It fits ok but when I resize the screen slowly (not too much) the PDF layer shrink.

**Comment by wojtekmaj** [comment]
And by default it will do that (but I'm planning to remove it for 5.0 because that causes more confusion than real benefits). You can adjust CSS for it not to resize the canvas/svg, or use a window resize event handler to provide proper dimensions for React-PDF for Text Layer to also be rendered smaller.

**Comment by alex-mironov** [comment]
@wojtekmaj can you please help to figure out what causes the issue with the text layer offset? The dimensions of container and page seem to be in line, but the text is shifted and the selection line height seems also quite big.
<img width="580" alt="Screen Shot 2019-10-18 at 17 10 47" src="https://user-images.githubusercontent.com/2544767/67101439-4b44d200-f1ca-11e9-8965-d579e45deda8.png">
I would be thankful for any ideas!

**Comment by alex-mironov** [comment]
<img width="387" alt="Screen Shot 2019-10-18 at 18 42 35" src="https://user-images.githubusercontent.com/2544767/67108393-155a1a80-f1d7-11e9-8576-ad62cb928b13.png">
From what I can see, span is positioned correctly, but the text itself gets pushed down.

**Comment by juanvalag** [comment]
Try these styles: 
![2019-10-27_194417](https://user-images.githubusercontent.com/49079712/67644759-60b8ab00-f8f2-11e9-8fb1-d88af4cf45da.jpg)

**Comment by jacksleight** [comment]
I was having an issue where the text layer was appearing offset vertically because the PDF was being rendered inside a parent that set `line-height` (to 1.5 in this instance), and I don't think react-pdf resets this.

![Screen Shot 2020-02-12 at 12 19 42](https://user-images.githubusercontent.com/126740/74334707-52ec4000-4d92-11ea-81d9-45fc7f86e9cc.png)

The fix was to reset `line-height` on the document wrapper:

```css
.react-pdf__Document {
    line-height: 1;
}
```

![Screen Shot 2020-02-12 at 12 20 03](https://user-images.githubusercontent.com/126740/74334630-318b5400-4d92-11ea-8823-b76028921d49.png)

**Comment by zdrukteinis** [comment]
Added `removeTextLayerOffset` function on page load success, provided by @nikonet :

```
function removeTextLayerOffset() {
  const textLayers = document.querySelectorAll(".react-pdf__Page__textContent");
    textLayers.forEach(layer => {
      const { style } = layer;
      style.top = "0";
      style.left = "0";
      style.transform = "";
  });
}

<Page onLoadSuccess={removeTextLayerOffset}/>
```


Also, added these styles (the key here is `opacity` as 0.1):

```
.react-pdf__Page__textContent span {
	opacity: 0.1;
}

.react-pdf__Page__textContent span::selection {
	background-color: blue;
}

.react-pdf__Document {
	line-height: initial;
}
```

Seems to work quite well:

![image](https://user-images.githubusercontent.com/21248613/75818393-760e7c00-5da1-11ea-84a8-d4851de6bd95.png)

**Comment by valeedmalik** [comment]
I needed to tweak the solution from @nikonet in order to get it to work.

```
function removeTextLayerOffset() {
  const textLayers = document.querySelectorAll('.react-pdf__Page__textContent');
  textLayers.forEach((layer) => {
    const { style } = layer;
    style.display = 'none';
  });
}

<Page onLoadSuccess={removeTextLayerOffset}/>
```

**Comment by AndyZhuAZ** [comment]
I still have this issue.

**Comment by komret** [comment]
I was also facing this issue and while @nikonet's tweak did help, I found the cause to be in the annotation layer not being styled properly. I forgot to import the stylesheet for it. BTW, docs metion the path `'react-pdf/dist/esm/Page/AnnotationLayer.css'`, but it was `'react-pdf/dist/Page/AnnotationLayer.css'` in my case.

Similar problem appeared when i zoomed in, causing the PDF to overflow its container. I solved this more or less the same way as @katiewoolston did, by applying `display: table` to the Page element.

**Comment by rahulIcreon** [comment]
> I had the same problem on window resize and scale changes. Solved it by calling a function that removes some of the CSS applied on the text-content page on each pageLoadSuccess. It seems to me that the default top, left and transform CSS properties on the textContent elements doesn't do anything useful. Those styles are inline, so needs to be changed with JS.
> 
> ```
> function removeTextLayerOffset() {
>   const textLayers = document.querySelectorAll(".react-pdf__Page__textContent");
>     textLayers.forEach(layer => {
>       const { style } = layer;
>       style.top = "0";
>       style.left = "0";
>       style.transform = "";
>   });
> }
> 
> <Page onLoadSuccess={removeTextLayerOffset}/>
> ```
How can we do this with TypeScript, please?

**Comment by DoguhanCiftciMaxim** [comment]
> > I had the same problem on window resize and scale changes. Solved it by calling a function that removes some of the CSS applied on the text-content page on each pageLoadSuccess. It seems to me that the default top, left and transform CSS properties on the textContent elements doesn't do anything useful. Those styles are inline, so needs to be changed with JS.
> > ```
> > function removeTextLayerOffset() {
> >   const textLayers = document.querySelectorAll(".react-pdf__Page__textContent");
> >     textLayers.forEach(layer => {
> >       const { style } = layer;
> >       style.top = "0";
> >       style.left = "0";
> >       style.transform = "";
> >   });
> > }
> > 
> > <Page onLoadSuccess={removeTextLayerOffset}/>
> > ```
> 
> How can we do this with TypeScript, please?
```

function removeTextLayerOffset() {
        const textLayers = window.document.querySelectorAll(".react-pdf__Page__textContent");
        textLayers.forEach((layer: any) => {
            const { style } = layer;
            style.top = "0";
            style.left = "0";
            style.transform = "";
        });
    }
```

**Comment by nico971** [comment]
For me solved by simply add
`<Page renderTextLayer={false} renderAnnotationLayer={false}/>`

**Comment by ritik-peoplelink** [comment]
> 
Yess It's working Perfectly

**Comment by aswathykrishna18** [comment]
Try importing the css files
`import 'react-pdf/dist/cjs/Page/AnnotationLayer.css';
import 'react-pdf/dist/cjs/Page/TextLayer.css';`

**Comment by CoderAWei** [comment]
> Try these styles: ![2019-10-27_194417](https://user-images.githubusercontent.com/49079712/67644759-60b8ab00-f8f2-11e9-8fb1-d88af4cf45da.jpg)

It worked, but the animation is disappear

**Comment by GarikHk** [comment]
Thank you for the clarification.

**Comment by hritikb27** [comment]
The issue seems to persist, although after trying @nikonet's solution the offset reduced, but I still get it and my need is to highlight the text on the page so I cannot hide the annotation or text layers.

I tried to use highlighting recipe provided in the docs but having same issue

![react-pdf](https://github.com/wojtekmaj/react-pdf/assets/86529959/a6cab69e-a240-44fd-bbab-56dd523346fe)

**Comment by fitzgibbonjack** [comment]
I was experiencing the same issue.. the text layer was slightly out of line. Fixed this by importing this file:

```import 'react-pdf/dist/Page/TextLayer.css';```

As per the documentation [here](https://github.com/wojtekmaj/react-pdf#support-for-text-layer)

**Comment by Klem3n** [comment]
Fixed the issue by importing this:
`import "react-pdf/dist/esm/Page/AnnotationLayer.js";
import "react-pdf/dist/esm/Page/TextLayer.js";`

**Comment by mttetc** [comment]
I've tried everything in this thread and unless I force the width to be exactly 596px, nothing is placed correctly, be it annotations or textlayer, it's kind of hard to know what's wrong here
